### ISSUE TITLE
NoClassDefFoundError: org/pac4j/core/util/FindBest

### ISSUE THREAD

**Issue by tasosioannidis** [pac4j/javalin-pac4j#228]
I've seen in previous issue that it's suggested to use Javalin 5.6.2 with javalin-pac4j 6.0.0 (which uses pac4j 5.7.0)

I added above, but I have runtime issue:

[JettyServerThreadPool-61] ERROR io.javalin.Javalin - Fatal error occurred while servicing http-request
java.lang.NoClassDefFoundError: org/pac4j/core/util/FindBest
	at org.pac4j.javalin.SecurityHandler.handle(SecurityHandler.java:43)
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
	at io.javalin.http.servlet.DefaultTasks.BEFORE$lambda$2$lambda$1$lambda$0(DefaultTasks.kt:19)
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: org.pac4j.core.util.FindBest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 35 more
	
	
My full dependencies are:
javalin: 5.6.2
javalin-pac4j: 6.0.0
pac4j-http 6.0.0-RC6
pac4j-jwt 5.7.0

I added code from https://github.com/pac4j/javalin-pac4j/blob/master/pom.xml, in my project

I have tried some combinations with no effect.

**Comment by tasosioannidis** [comment]
Update:
I have removed explicit pac4j-http and pac4j-jwt, and now build fails on missing CallContext:

```
import org.pac4j.core.context.CallContext;
//...

import java.util.Optional;

public class TrivialUserPassAuthenticator implements Authenticator {..}
```

**Comment by tasosioannidis** [comment]
Update 2:

I followed readme instructions (master branch):

> You need to add a dependency for:

> the javalin-pac4j library (groupId: org.pac4j, version: 6.0.0)
> the appropriate pac4j [submodules](http://www.pac4j.org/docs/clients.html) (groupId: org.pac4j, version: 5.7.1): pac4j-oauth for OAuth support (Facebook, Twitter...), pac4j-cas for CAS support, pac4j-ldap for LDAP authentication, etc.

and still reproduced above missing "org.pac4j.core.context.CallContext" error.

After using it's 6.0 equivalent WebContext (also picked whole TrivialUserPassAuthenticator), it seems like I have a working build/run and security/auth.

**Comment by leleuj** [comment]
You also need to add the `pac4j-core` dependency in the same version as your other pac4j dependencies (5.7.0 it seems).
