### ISSUE TITLE
FindBest runtime error

### ISSUE THREAD

**Issue by tasosioannidis** [pac4j/javalin-pac4j#235]
This is code from ExampleConfigFactory.java.
I have integrated this in my project.

import org.pac4j.core.credentials.TokenCredentials;
//..
        HeaderClient headerClient = new HeaderClient("Authorization", (Authenticator) (ctx, credentials) -> {
            String token = ((TokenCredentials) credentials).getToken();
            if (CommonHelper.isNotBlank(token)) {
                CommonProfile profile = new CommonProfile();
                profile.setId(token);
                credentials.setUserProfile(profile);  <----- cannot find symbol error locally
                return Optional.of(credentials);
            }
            return Optional.empty();
        });

I get above build time error,
with these dependencies:

         <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
            <version>5.6.3</version>
         </dependency>
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>javalin-pac4j</artifactId>
            <version>6.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-http</artifactId>
            <version>5.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-jwt</artifactId>
            <version>5.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-core</artifactId>
            <version>5.7.0</version>
        </dependency>

Same with replacing 5.7.0 with 5.7.1  (in above 3 places), as proposed in README
https://github.com/pac4j/javalin-pac4j

Tried replacing 5.7.0 with 6.0.0-RC1 until 6.0.0-RC4 (in above 3 places) -> Same error

Now trying same with 6.0.0-RC5 up to 6.0.0-RC9. Builds and starts up. But when I call an endpoint, I get the FindBest error:

java.lang.NoClassDefFoundError: org/pac4j/core/util/FindBest
	at org.pac4j.javalin.SecurityHandler.handle(SecurityHandler.java:43)
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
	at io.javalin.http.servlet.DefaultTasks.BEFORE$lambda$2$lambda$1$lambda$0(DefaultTasks.kt:19)
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.ClassNotFoundException: org.pac4j.core.util.FindBest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 36 more

All above happen also with Javalin 5.6.2

**Comment by leleuj** [comment]
You can't upgrade to pac4j v6 with javalin-pac4j v6, you must use pac4j v5.7.1.

**Comment by tasosioannidis** [comment]
Hi @leleuj 

As I said here:

>      <dependency>
>         <groupId>io.javalin</groupId>
>         <artifactId>javalin</artifactId>
>         <version>5.6.3</version>
>      </dependency>
>     <dependency>
>         <groupId>org.pac4j</groupId>
>         <artifactId>javalin-pac4j</artifactId>
>         <version>6.0.0</version>
>     </dependency>
>     <dependency>
>         <groupId>org.pac4j</groupId>
>         <artifactId>pac4j-http</artifactId>
>         <version>5.7.0</version>
>     </dependency>
>     <dependency>
>         <groupId>org.pac4j</groupId>
>         <artifactId>pac4j-jwt</artifactId>
>         <version>5.7.0</version>
>     </dependency>
>     <dependency>
>         <groupId>org.pac4j</groupId>
>         <artifactId>pac4j-core</artifactId>
>         <version>5.7.0</version>
>     </dependency>
>     
> Same with replacing 5.7.0 with 5.7.1 (in above 3 places), as proposed in README

I imply that I already tried javalin-pac4j 6.0 with pac4j 5.7.1

**Comment by leleuj** [comment]
And what error do you get with javalin 5.6.3, javalin-pac4j v6.0.0 and pac4j-* v5.7.0?

**Comment by tasosioannidis** [comment]
I get a build error "cannot find symbol"

-------------------------------------------

import org.pac4j.core.credentials.TokenCredentials;
//..
HeaderClient headerClient = new HeaderClient("Authorization", (Authenticator) (ctx, credentials) -> {
String token = ((TokenCredentials) credentials).getToken();
if (CommonHelper.isNotBlank(token)) {
CommonProfile profile = new CommonProfile();
profile.setId(token);
credentials.setUserProfile(profile); <----- **cannot find symbol error locally**
return Optional.of(credentials);
}
return Optional.empty();
});

I get above build time error,
-------------------------------------------

**Comment by leleuj** [comment]
This is very strange as the `setUserProfile` method has always been part of the `Credentials` component.

Can you share some small project on github.com to demonstrate the problem? Thanks

**Comment by tasosioannidis** [comment]
Hi @leleuj 

Before I share the example project, I have solved the runtime error by:

```
        <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>javalin-pac4j</artifactId>
            <version>7.0.0-SNAPSHOT</version>
        </dependency>
```

Does that help identify the problem?

Is that version ok to use?

**Comment by leleuj** [comment]
That does not really help, but anyway, using these versions is OK since the final release is coming soon... Can you use pac4j v6.0.0-RC10 as well? Thanks

**Comment by leleuj** [comment]
Forget my previous message: RC10 is not compatible yet: https://github.com/pac4j/javalin-pac4j/actions/runs/6954349905/job/18920998281?pr=236

**Comment by tasosioannidis** [comment]
Ok @leleuj 

I wish a had time to prepare/share an example project.
Since the aforementioned versions are OK, I can continue with these.

**Comment by leleuj** [comment]
OK. No problem. Thanks for your time.
